### ISSUE TITLE
Release version?

### ISSUE THREAD

**Issue by sttawm** [scalapb/scalapb-validate#109]
What's the thinking behind having a snapshot version has opposed to a release version? 

Isn't it a bit risky to depend on a snapshot that could be updated at any time?

**Comment by thesamet** [comment]
Snapshots (for scalapb-validate) are immutable, the exact commit hash is part of the version name, see [this listing]( https://oss.sonatype.org/content/repositories/snapshots/com/thesamet/scalapb/scalapb-validate-core_2.13/), so there's no risk of an artifact being updated after you pinned one.

I suspect that your questions rises from this section in the [main README](https://github.com/scalapb/scalapb-validate#adding-the-latest-snapshot-release-to-your-project) file - can you confirm my assumption? If so, the docs are out of date, we do have stable releases now and the [primary documentation](https://scalapb.github.io/docs/validation) doesn't call out to use snapshots.

**Comment by sttawm** [comment]
Yes I can confirm your assumption -- I did get confused by the README. Thanks for the clarification, in retrospect I should have also checked the [mvnrepository listing](https://mvnrepository.com/artifact/com.thesamet.scalapb/scalapb-validate-codegen_2.13/0.3.1)
