### ISSUE TITLE
Validator[A] autogenerated code

### ISSUE THREAD

**Issue by Eli-Golin** [scalapb/scalapb-validate#222]
The autogenerated 
`implicit val validator:scalapb.validate.Validator[SomeType] = fully.quelified.name.SomeTypeValidator`, inside the companion object , **is not serialisable**.
When using frameworks such as Spark/Flink, it prevents us from providing it as an implicit evidence to methods which define the execution graph.

I think that changing the implementation from `object` to `case object` on your side would do the trick.

Tnx.
 
https://github.com/scalapb/scalapb-validate/blob/02bb01e406cfa3c4d7969abe6af8c5347f610446/code-gen/src/main/scala/scalapb/validate/compiler/CodeGenerator.scala#L141

**Comment by thesamet** [comment]
Changing it from `implicit val` to `implicit def` would be my preferred approach in this case (in my mind case objects are to signal that the object is data, such as enum).

Do you know if that's the only reason why the companion is not serializable? With validation turned off would it serialize?

**Comment by Eli-Golin** [comment]
Yes. I have actually built a local copy of your code and it works perfectly.
Regarding the implicit method, it sounds great.

**Comment by Eli-Golin** [comment]
@thesamet when do you plan the next release?

**Comment by thesamet** [comment]
Releases happen around new features or updating versions of dependencies. Since this change is small, it's reasonable to get a new release some time next week with bumped up version of cats and other deps.

**Comment by plaflamme** [comment]
@thesamet Looks like `0.3.3` was released here, but it doesn't appear in maven central, the latest is still `0.3.2` [over there.](https://repo1.maven.org/maven2/com/thesamet/scalapb/scalapb-validate-codegen_3/)

**Comment by thesamet** [comment]
Yes, looks like the release process of 0.3.3 had failed. I'll cut a new one soon.

**Comment by thesamet** [comment]
0.3.3 is now available.
