### ISSUE TITLE
Versioning Questions

### ISSUE THREAD

**Issue by AlexWeinstein92** [scalapb/scalapb-validate#290]
I've read that required fields were removed in proto3 because the lack of `Option` wrapping the field was leading to versioning headaches. The issue being without `Option` wrapping the field on the Java/Scala/whatver-non-proto-language level, if you want to alter it you have to remove the field , reserve the field number, & create a new one with a new field number.

As such I am noticing that even things like string validation rules lead to non-`Option`-wrapped fields on the non-proto level, and wondering if I might run into versioning issues once I hit deployment and decide to alter the validation on some of these fields, or change the data type, Any help in answering this question before I hit deployment would be greatly appreciated.

Note: I am using `validation-at-construction: true`

Also, sorry if this is not the proper forum for this question, I didn't see any link to a chat so feel free to close the issue before responding.

**Comment by thesamet** [comment]
Hi @AlexWeinstein92 , in proto3 primitives (such as strings, numbers) are optional by default and their Scala (or Java representation) is without an `Option` wrapping. If a field is missing in a binary representation, it's value would be a default value for the type - such as empty string, or 0 if it's a number.

Assume you remove fields, but you have old code that parses and validates - it will work just fine - those empty values will be validated and based on your rules the validation will pass or fail. However, if you generate Scala case classes and validation at the same time in your build, you may run into a situation where the validation code tries to validate a field that doesn't exist in the scala class and run into "NoSuchMethod" issues. As long, as you generate Scala and validation code at the same time - you should be fine.

**Comment by AlexWeinstein92** [comment]
@thesamet Thanks for the quick response. Wondering though if maybe there was a typo in second last sentence? You say "if you generate at same time there could be NoSuchMethod" and then immediately follow that with "as long as you generate at same time you're fine" - did you meant to say "if you *don't* generate at same time there could be NoSuchMethod"

**Comment by thesamet** [comment]
You are right. I had this error in the original response, thanks for catching. I edited it and it's now correct.
