### ISSUE TITLE
[0.2.x-preview] raise an IllegalArgumentException when a NonEmptyCollection is empty

### ISSUE THREAD

**Issue by gontard** [scalapb/scalapb-validate#57]
When both `validate_at_construction` and `cats_transforms` are true, the raised exception when a PGV rule is not fulfilled are:
 - `[(validate.rules).repeated.min_items = 1];`  => [`com.google.protobuf.InvalidProtocolBufferException`](https://github.com/scalapb/scalapb-validate/blob/5ef46f31bb7dd4b660b707d41e1e4e84252b307f/cats/src/main/scala/scalapb/validate/cats/CatAdapters.scala#L13)
 - anything else => [`java.lang.IllegalArgumentException`](https://github.com/scalapb/scalapb-validate/blob/5ef46f31bb7dd4b660b707d41e1e4e84252b307f/core/src/main/scala/scalapb/validate/Validator.scala#L84)

Demo in 
https://github.com/gontard/scalapb-validate-demo/commit/3efcf74f9547d229080f0aa7ba9ea514f6517f2a

**Comment by gontard** [comment]
Not directly related but to facilitate exception handling, it would be nice if scalapb-validate raises a specific Exception (could be a subtype of `IllegalArgumentException`)

**Comment by thesamet** [comment]
This should be addressed in 0.2.0-preview4. The change also requires updating ScalaPB's compilerplugin to 0.2.0-preview4 and regenerating all code.

All exceptions raised are subclasses on `ValidationException`, which is in turn a subclass of `InvalidProtocolBufferException`.

**Comment by gontard** [comment]
Fixed in https://github.com/scalapb/scalapb-validate/commit/368f41ee14fb9d7867594934e7b75e4f83992d94
