### ISSUE TITLE
Support new options

### ISSUE THREAD

**Issue by bjaglin** [scalapb/scalapb-validate#67]
New options have been introduced upstream on master
- [`ignored`](https://github.com/envoyproxy/protoc-gen-validate/commit/538267e6e8c985a678e03c42c02b801e9eef8d3c#diff-79dbefd0936fb92e1d1e8dc66ab3f476a4010c0c8fe01e6d98d4c6fe662c64b7R17)
- [`ignore_empty`](https://github.com/envoyproxy/protoc-gen-validate/pull/412/files#diff-79dbefd0936fb92e1d1e8dc66ab3f476a4010c0c8fe01e6d98d4c6fe662c64b7R772-R774)

When a release is cut and the upstream dependency is bumped, they should be supported

**Comment by thesamet** [comment]
👍 . BTW, ScalaPB-validate is tested against the same 900+ test case suite that is used for PGV. PGV has a test executor that invokes a test target, and it invokes it for each test case (sending the proto to test over stdin). See https://github.com/scalapb/scalapb-validate/blob/master/e2e/src/test/scala/scalapb/validate/ScalaHarness.scala and how it is invoked in CI.

**Comment by bjaglin** [comment]
Available in 0.3.0

**Comment by thesamet** [comment]
It's a bit unexpected since I have not implemented support for `ignored` and `ignored_empty` yet the test case pass. Any thoughts why? Reopening so I remember to take a look at it.

**Comment by bjaglin** [comment]
I closed too fast indeed. For some reasons, I thought scalapb-validate was built against the freshly-released https://github.com/envoyproxy/protoc-gen-validate/releases/tag/v0.5.0, but it's not. It seems that 0.5.0 hasn't been cut for Java yet.

**Comment by thesamet** [comment]
v0.3.2 is on the way to maven, includes support for these options, along with a bump of PGV to 0.6.1, and Scala 3 support.
