### ISSUE TITLE
scalapb-validate integration with akka-grpc

### ISSUE THREAD

**Issue by thesamet** [scalapb/scalapb-validate#70]
akka-grpc defaults to compiling with `flat_package=true`. This results in user's generated code to reference the flat-package location of Scala sources generated by `validate.proto`. However, the `validate.proto` shipped with `scalapb-validate`, through `common-protos` defaults to `flat_package=false`.

The goal of this ticket is to come up with a straightforward way for akka-grpc users to use scalapb-validate.

**Comment by bjaglin** [comment]
Thanks for opening this to centralize the discussion. I have started thinking about this, see https://github.com/scalapb/ScalaPB/pull/873#issuecomment-768447926 & https://github.com/scalapb/protoc-bridge/pull/158

**Comment by thesamet** [comment]
One workaround that would work with current versions is to have users add package-scoped option to disable `flat_package` for validate:

```
package validate;
import "scalapb/scalapb.proto";
option (scalapb.options) = {
  scope: PACKAGE
  flat_package: false
};
```

**Comment by bjaglin** [comment]
We have settled on a variant of idea 1 (since we didn't want to change all source code): disable `flat_package` at the generator level, but enable it selectively for our packages.

There is a gotcha with that, as Akka gRPC generators don't seem to handle package-level `flat_package` so `flat_package` needs to be disabled only for the ScalaPB gen. I was planning to open a PR on akka-grpc to fix that (I assume `DescriptorImplicits` is not used properly), update https://github.com/bjaglin/sbt-protoc/commit/53dbd6a87e393209a3e55ee755de83706638b7fd#diff-bbd8a5163e4909c406d2fd2b12cca4345f91859fae3676fd8ee189d121e2c9f1R2-R10 (which is broken at the moment), and write a scripted there.

**Comment by bjaglin** [comment]
Idea 1 does not seem to work as activating `flat_package` through the generator option takes precedence over the file/package-level setting: https://github.com/scalapb/ScalaPB/blob/05b5aea520e621d0946ca08acc760bf306546199/compiler-plugin/src/main/scala/scalapb/compiler/DescriptorImplicits.scala#L917

**Comment by thesamet** [comment]
> https://github.com/scalapb/ScalaPB/blob/05b5aea520e621d0946ca08acc760bf306546199/compiler-plugin/src/main/scala/scalapb/compiler/DescriptorImplicits.scala#L909-L910

I think we should change to make it possible for the the file-level to override with a `false` value.

**Comment by bjaglin** [comment]
> There is a gotcha with that, as Akka gRPC generators don't seem to handle package-level `flat_package`

ScalaPB extensions are currently not registered in akka-grpc so the compiler plugin does not see them, I am sending a PR to akka-grpc shortly.

**Comment by thesamet** [comment]
> ScalaPB extensions are currently not registered in akka-grpc so the compiler plugin does not see them, I am sending a PR to akka-grpc shortly

Thanks! Does it impact the solution? akka-grpc might erroneously think that 'validate' is compiled with flat_package - but does the code it generates references it?

**Comment by bjaglin** [comment]
It makes what I described in https://github.com/scalapb/scalapb-validate/issues/70#issuecomment-768478263 easier (the [scripted](https://github.com/akka/akka-grpc/pull/1253/files#diff-8e096567ca4244c0682cd76af6a3647beb7bfb64415e935cbf81e9d52035e4ee) is precisely what we are using to workaround this issue).

I believe it does not impact in any way the solution you are implementing.

**Comment by bjaglin** [comment]
I think we can close this now that https://github.com/akka/akka-grpc/pull/1264 verifies the integration with sbt-protoc 1.0.1 / scalapb-validate 0.2.1. Thanks for making the integration seamless!

**Comment by bjaglin** [comment]
Actually there is still one thing missing: usage of `scalapb/validate.proto` to customize `scalapb-validate` through file/package-level options is not possible out of the box from akka-grpc.
```proto
import "scalapb/scalapb.proto";
import "scalapb/validate.proto";

option (scalapb.options) = {
    scope: FILE
    [scalapb.validate.file] {
        validate_at_construction: true
    }
};
```
```
[info] [error] /tmp/sbt_70a87d09/target/scala-2.12/akka-grpc/main/example/myapp/helloworld/grpc/HelloworldProto.scala:11:22: object ValidateProto is not a member of package scalapb.validate
[info] [error]     scalapb.validate.ValidateProto,
```

From my understanding, we should either
1. have `scalapb-validate-core` expose its own option proto
1. update https://github.com/scalapb/ScalaPB/blob/05b5aea520e621d0946ca08acc760bf306546199/compiler-plugin/src/main/scala/scalapb/compiler/DescriptorImplicits.scala#L909-L910
```diff
     private def isNonFlatDependency =
-      (file.getPackage == "google.protobuf") || (file.getPackage == "scalapb")
+      (file.getPackage == "google.protobuf") || (file.getPackage.startsWith("scalapb"))
```

Happy to open a PR for (2) on ScalaPB as it looks like the easiest.

**Comment by thesamet** [comment]
v0.2.2 is released with the manifest option - can you try it out?

**Comment by bjaglin** [comment]
> v0.2.2 is released with the manifest option - can you try it out?

I just verified the fix with https://github.com/akka/akka-grpc/pull/1264/commits/e4a39c6f37e7351ce62ec9ffb9a56603856f0918, thanks for the quick turnaround!

And this time, I think we are good to close this.
